const mongoose = require("mongoose");
const FAABSchema = new mongoose.Schema({
    id:String,
    Company_name:String,
    Headquarter:String,
    ISIN:String,
    Agricultural_inputs:String,
    Agricultural_products_and_commodities:String,
    Animal_proteins:String,
    Food_and_beverage_manufacturers_processors:String,
    Food_retailers:String,
    Restaurants_and_food_service:String,
    Rank:String,
    Score:String,
    MA1:String,
    MA2:String,
    MA3:String,
    MA4:String,
    A1:String,
    A2:String,
    A3:String,
    B1:String,
    B2:String,
    B3:String,
    B4:String,
    B5:String,
    B6:String,
    B7:String,
    B8:String,
    B9:String,
    B10:String,
    B11:String,
    B12:String,
    C1:String,
    C2:String,
    C3:String,
    C4:String,
    C5:String,
    C6:String,
    D1:String,
    D2:String,
    D3:String,
    D4:String,
    D5:String,
    D6:String,
    D7:String,
    D8:String,
    D9:String,
    D10:String,
    D11:String,
    D12:String,
    D13:String,
    D14:String,
    D15:String,
    D16:String,
    D17:String,
    D18:String,
    D19:String,
    D20:String,
    D21:String,
    D22:String,
    D23:String,
    D24:String
})

const FAABResults = mongoose.model("FAABRESULT", FAABSchema, "FAABRESULTS");

module.exports = FAABResults;