const mongoose = require("mongoose");
const FAABSchema = new mongoose.Schema({
    id:String,
    Company_name:String,
    Headquarter:String,
    ISIN:String,
    Agricultural_inputs:String,
    Agricultural_products_and_commodities:String,
    Animal_proteins:String,
    Food_and_beverage_manufacturers_processors:String,
    Food_retailers:String,
    Restaurants_and_food_service:String,
    Rank:String,
    Score:String,
    MA_ONE:String,
    MA_TWO:String,
    MA_THREE:String,
    MA_FOUR:String,
    A_ONE:String,
    A_TWO:String,
    A_THREE:String,
    B_ONE:String,
    B_TWO:String,
    B_THREE:String,
    B_FOUR:String,
    B_FIVE:String,
    B_SIX:String,
    B_SEVEN:String,
    B_EIGHT:String,
    B_NINE:String,
    B_TEN:String,
    B_ELEVEN:String,
    B_TWELVE:String,
    C_ONE:String,
    C_TWO:String,
    C_THREE:String,
    C_FOUR:String,
    C_FIVE:String,
    C_SIX:String,
    D_ONE:String,
    D_TWO:String,
    D_THREE:String,
    D_FOUR:String,
    D_FIVE:String,
    D_SIX:String,
    D_SEVEN:String,
    D_EIGHT:String,
    D_NINE:String,
    D_TEN:String,
    D_ELEVEN:String,
    D_TWELVE:String,
    D_THIRTEEN:String,
    D_FOURTEEN:String,
    D_FIFTEEN:String,
    D_SIXTEEN:String,
    D_SEVENTEEN:String,
    D_EIGHTEEN:String,
    D_NINETEEN:String,
    D_TWENTY:String,
    D_TWENTYONE:String,
    D_TWENTYTWO:String,
    D_TWENTYTHREE:String,
    D_TWENTYFOUR:String
})

const FAABResults = mongoose.model("FAABDATA", FAABSchema, "FAABDATAS");

module.exports = FAABResults;